apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-api-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: todo
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
