apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 80         
      targetPort: 3000 
  type: ClusterIP
