name: CI/CD Pipeline - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      image_name: todo-api
      image_tag: latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code (shallow clone)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8/deployment.yml
          kubectl apply -f k8/service.yml
          
          
      - name: Deploy Prometheus Monitoring
        run: |
          kubectl apply -f k8/prometheus-deployment.yml
          kubectl apply -f k8/prometheus-service.yaml
